server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: front
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**, /menus/**, /orderHistrories/**
        - id: Store
          uri: http://localhost:8082
          predicates:
            - Path=/storeMgmts/**, /orderInfos/**
        - id: Pay
          uri: http://localhost:8083
          predicates:
            - Path=/pays/**, 
        - id: Customer
          uri: http://localhost:8084
          predicates:
            - Path=/payMgmts/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: front
          uri: http://front:8080
          predicates:
            - Path=/orders/**, /menus/**, /orderHistrories/**
        - id: Store
          uri: http://store:8080
          predicates:
            - Path=/storeMgmts/**, /orderInfos/**
        - id: Pay
          uri: http://pay:8080
          predicates:
            - Path=/pays/**, 
        - id: Customer
          uri: http://customer:8080
          predicates:
            - Path=/payMgmts/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
